import Navigation from '../_components/navigation';
import { AuthProvider } from '../context/auth.context';
import { ClientSelectProvider } from '../context/client.context';

export const metadata = {
  title: 'Welcome to front',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <ClientSelectProvider>
        <Navigation />
        {children}
      </ClientSelectProvider>
    </AuthProvider>
  );
}
