import './global.css';
import { AuthProvider } from './context/auth.context';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Welcome to front',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body>
        <AuthProvider>{children}</AuthProvider>
        <Toaster position="bottom-right"/>
      </body>
    </html>
  );
}
